create table games
(
  id               bigint generated by default as identity primary key,
  tournament_id    bigint not null,
  first_player_id  bigint not null,
  second_player_id bigint not null,
  start_date_time  timestamp,
  final_score      text,
  winner_id        bigint,
  duration         int,
  stage            int
)